-- APIGuard schema (Postgres; H2 runs in PostgreSQL compatibility mode for tests).

create table api (
    id         bigint generated by default as identity primary key,
    name       varchar(255) not null unique,
    repo       varchar(512),
    spec_path  varchar(512),
    created_at timestamp not null default current_timestamp
);

create table spec_version (
    id            bigint generated by default as identity primary key,
    api_id        bigint not null references api (id),
    git_sha       varchar(64),
    version_label varchar(255),
    raw_spec      text,
    created_at    timestamp not null default current_timestamp
);

create table change_record (
    id              bigint generated by default as identity primary key,
    api_id          bigint references api (id),
    from_version_id bigint references spec_version (id),
    to_version_id   bigint references spec_version (id),
    classification  varchar(32) not null,
    kind            varchar(64) not null,
    endpoint        varchar(512),
    json_pointer    varchar(512),
    field           varchar(255),
    description     varchar(1024),
    created_at      timestamp not null default current_timestamp
);
create index idx_change_api on change_record (api_id);

create table changelog_entry (
    id            bigint generated by default as identity primary key,
    api_id        bigint references api (id),
    to_version_id bigint references spec_version (id),
    version_label varchar(255),
    markdown      text not null,
    published_at  timestamp not null default current_timestamp
);

create table dependency_manifest (
    id            bigint generated by default as identity primary key,
    consumer      varchar(255) not null unique,
    owner_team    varchar(255),
    slack_channel varchar(255),
    source_repo   varchar(512),
    updated_at    timestamp not null default current_timestamp
);

create table dependency_manifest_reviewer (
    manifest_id bigint not null references dependency_manifest (id),
    reviewer    varchar(255) not null
);

create table dependency_edge (
    id          bigint generated by default as identity primary key,
    manifest_id bigint not null references dependency_manifest (id),
    api_name    varchar(255) not null,
    endpoint    varchar(512) not null,
    field       varchar(255)
);
create index idx_edge_lookup on dependency_edge (api_name, endpoint, field);

create table field_source (
    id                bigint generated by default as identity primary key,
    api_name          varchar(255) not null,
    endpoint          varchar(512) not null,
    field             varchar(255) not null,
    upstream_api      varchar(255),
    upstream_endpoint varchar(512),
    upstream_field    varchar(255)
);
create index idx_field_source_lookup on field_source (api_name, endpoint, field);

create table blast_result (
    id          bigint generated by default as identity primary key,
    pr_ref      varchar(255),
    change_id   bigint references change_record (id),
    consumer    varchar(255),
    notified_at timestamp
);
