-- Repo URLs the user registers as scan sources (GitHub/Bitbucket/local), so "Sync everything" can
-- re-scan them alongside Anypoint on demand. Persisted so they survive restarts (desktop/prod).
create table scan_source (
    id         bigint generated by default as identity primary key,
    url        varchar(1024) not null unique,
    created_at timestamp not null default current_timestamp
);
