create table audit_event (
    id         bigint generated by default as identity primary key,
    ts         timestamp not null default current_timestamp,
    actor      varchar(255),
    action     varchar(64)  not null,
    subject    varchar(512),
    detail     varchar(2048)
);

create index audit_event_ts_idx on audit_event (ts);
