package com.apiguard.server.service;

import com.apiguard.core.catalog.ApiLayer;
import com.apiguard.core.catalog.EstateInsights;
import com.apiguard.server.domain.ChangelogEntryEntity;
import com.apiguard.server.repo.ChangelogRepository;
import com.apiguard.server.web.Dtos;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@Service
public class ReportService {

    private static final DateTimeFormatter DATE =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm 'UTC'").withZone(ZoneId.of("UTC"));
    private static final int TOP_APIS = 10;
    private static final int RECENT_CHANGELOGS = 10;

    private final GraphService graph;
    private final InsightsService insights;
    private final ChangelogRepository changelogs;

    public ReportService(GraphService graph, InsightsService insights, ChangelogRepository changelogs) {
        this.graph = graph;
        this.insights = insights;
        this.changelogs = changelogs;
    }

    @Transactional(readOnly = true)
    public String markdown() {
        Dtos.GraphDto g = graph.build();
        List<EstateInsights.Finding> findings = insights.computeFor(g);
        StringBuilder md = new StringBuilder();

        md.append("# Wakegraph estate report\n\n");
        long breakingEdges = g.edges().stream().filter(e -> "breaking".equals(e.risk())).count();
        md.append('_').append(DATE.format(java.time.Instant.now()))
                .append(" · ").append(g.nodes().size()).append(" nodes · ")
                .append(g.edges().size()).append(" dependencies · ")
                .append(breakingEdges).append(" carrying a breaking change_\n\n");

        atAGlance(md, g);
        governance(md, findings);
        topApis(md, g);
        consumers(md, g);
        recentChangelogs(md);

        md.append("---\n_Generated by Wakegraph — blast radius, governance and changelogs for your Mule estate._\n");
        return md.toString();
    }

    private void atAGlance(StringBuilder md, Dtos.GraphDto g) {
        md.append("## Estate at a glance\n\n");
        Map<String, Long> byLayer = new LinkedHashMap<>();
        for (ApiLayer layer : ApiLayer.values()) {
            long n = g.nodes().stream().filter(x -> layer.name().equals(x.layer())).count();
            if (n > 0) {
                byLayer.put(layer.label(), n);
            }
        }
        md.append("| Layer | Count |\n|---|---:|\n");
        byLayer.forEach((label, n) -> md.append("| ").append(label).append(" | ").append(n).append(" |\n"));
        long standalone = g.nodes().stream()
                .filter(n -> n.dependsOn() == 0 && n.dependedOnBy() == 0).count();
        if (standalone > 0) {
            md.append("\n").append(standalone).append(" node(s) currently have no recorded dependency.\n");
        }
        md.append('\n');
    }

    private void governance(StringBuilder md, List<EstateInsights.Finding> findings) {
        md.append("## Governance findings\n\n");
        if (findings.isEmpty()) {
            md.append("✅ None — the estate follows API-led direction, has no dependency cycles ")
                    .append("and no change hotspots.\n\n");
            return;
        }
        for (String severity : List.of("high", "medium", "info")) {
            List<EstateInsights.Finding> of = findings.stream()
                    .filter(f -> f.severity().equals(severity)).toList();
            if (of.isEmpty()) {
                continue;
            }
            String badge = switch (severity) {
                case "high" -> "🟥 High";
                case "medium" -> "🟧 Medium";
                default -> "ℹ️ Info";
            };
            md.append("### ").append(badge).append('\n');
            for (EstateInsights.Finding f : of) {
                md.append("- **").append(f.title()).append("**  \n  ").append(f.detail()).append('\n');
            }
            md.append('\n');
        }
    }

    private void topApis(StringBuilder md, Dtos.GraphDto g) {
        List<Dtos.GraphNode> top = g.nodes().stream()
                .filter(n -> n.dependedOnBy() > 0)
                .sorted(Comparator.comparingInt(Dtos.GraphNode::dependedOnBy).reversed())
                .limit(TOP_APIS)
                .toList();
        if (top.isEmpty()) {
            return;
        }
        md.append("## Most depended-on APIs\n\n");
        md.append("| API | Layer | Consumers | Owner |\n|---|---|---:|---|\n");
        for (Dtos.GraphNode n : top) {
            md.append("| `").append(n.id()).append("` | ").append(layerLabel(n.layer()))
                    .append(" | ").append(n.dependedOnBy())
                    .append(" | ").append(n.ownerTeam() == null ? "—" : n.ownerTeam()).append(" |\n");
        }
        md.append('\n');
    }

    private void consumers(StringBuilder md, Dtos.GraphDto g) {
        Map<String, List<Dtos.GraphEdge>> byProvider = new LinkedHashMap<>();
        for (Dtos.GraphEdge e : g.edges()) {
            byProvider.computeIfAbsent(e.to(), k -> new java.util.ArrayList<>()).add(e);
        }
        if (byProvider.isEmpty()) {
            return;
        }
        md.append("## Who consumes what\n\n");
        byProvider.entrySet().stream()
                .sorted((a, b) -> Integer.compare(b.getValue().size(), a.getValue().size()))
                .forEach(entry -> {
                    md.append("### `").append(entry.getKey()).append("` — ")
                            .append(entry.getValue().size()).append(" consumer(s)\n");
                    for (Dtos.GraphEdge e : entry.getValue()) {
                        md.append("- `").append(e.from()).append('`');
                        if (!e.via().isEmpty()) {
                            md.append(" via ").append(String.join("; ", e.via()));
                        }
                        if ("breaking".equals(e.risk())) {
                            md.append(" ⚠️ *a recent change breaks this consumer*");
                        }
                        md.append('\n');
                    }
                    md.append('\n');
                });
    }

    private void recentChangelogs(StringBuilder md) {
        List<ChangelogEntryEntity> recent = changelogs.findAllByOrderByPublishedAtDesc().stream()
                .limit(RECENT_CHANGELOGS).toList();
        if (recent.isEmpty()) {
            return;
        }
        md.append("## Recent changelogs\n\n");
        md.append("| Published | API | Version |\n|---|---|---|\n");
        for (ChangelogEntryEntity e : recent) {
            md.append("| ").append(DATE.format(e.getPublishedAt()))
                    .append(" | `").append(e.getApi() == null ? "?" : e.getApi().getName())
                    .append("` | ").append(e.getVersionLabel() == null ? "—" : e.getVersionLabel())
                    .append(" |\n");
        }
        md.append('\n');
    }

    private static String layerLabel(String layer) {
        try {
            return ApiLayer.valueOf(layer).label();
        } catch (IllegalArgumentException | NullPointerException e) {
            return layer == null ? "—" : layer;
        }
    }
}
